/**
 * gradeSubjectData: 年级／科目数据
 */
const gradeSubjectData = [{
    "val":"0",
    "prop":"年级"
},{
    "val":"6",
    "prop":"高三",
    "subject":[{
        "val":"1",
        "prop":"语文"
    },{
        "val":"2",
        "prop":"数学"
    },{
        "val":"3",
        "prop":"英语"
    },{
        "val":"4",
        "prop":"物理"
    },{
        "val":"5",
        "prop":"化学"
    },{
        "val":"6",
        "prop":"历史"
    },{
        "val":"7",
        "prop":"地理"
    },{
        "val":"8",
        "prop":"生物"
    },{
        "val":"9",
        "prop":"政治"
    }]
},{
    "val":"5",
    "prop":"高二",
    "subject":[{
        "val":"1",
        "prop":"语文"
    },{
        "val":"2",
        "prop":"数学"
    },{
        "val":"3",
        "prop":"英语"
    },{
        "val":"4",
        "prop":"物理"
    },{
        "val":"5",
        "prop":"化学"
    },{
        "val":"6",
        "prop":"历史"
    },{
        "val":"7",
        "prop":"地理"
    },{
        "val":"8",
        "prop":"生物"
    },{
        "val":"9",
        "prop":"政治"
    }]
},{
    "val":"4",
    "prop":"高一",
    "subject":[{
        "val":"1",
        "prop":"语文"
    },{
        "val":"2",
        "prop":"数学"
    },{
        "val":"3",
        "prop":"英语"
    },{
        "val":"4",
        "prop":"物理"
    },{
        "val":"5",
        "prop":"化学"
    },{
        "val":"6",
        "prop":"历史"
    },{
        "val":"7",
        "prop":"地理"
    },{
        "val":"8",
        "prop":"生物"
    },{
        "val":"9",
        "prop":"政治"
    }]
},{
    "val":"3",
    "prop":"初三",
    "subject":[{
        "val":"1",
        "prop":"语文"
    },{
        "val":"2",
        "prop":"数学"
    },{
        "val":"3",
        "prop":"英语"
    },{
        "val":"4",
        "prop":"物理"
    },{
        "val":"5",
        "prop":"化学"
    },{
        "val":"6",
        "prop":"历史"
    },{
        "val":"7",
        "prop":"地理"
    },{
        "val":"8",
        "prop":"生物"
    },{
        "val":"9",
        "prop":"政治"
    },{
        "val":"12",
        "prop":"科学"
    }]
},{
    "val":"2",
    "prop":"初二",
    "subject":[{
        "val":"1",
        "prop":"语文"
    },{
        "val":"2",
        "prop":"数学"
    },{
        "val":"3",
        "prop":"英语"
    },{
        "val":"4",
        "prop":"物理"
    },{
        "val":"5",
        "prop":"化学"
    },{
        "val":"6",
        "prop":"历史"
    },{
        "val":"7",
        "prop":"地理"
    },{
        "val":"8",
        "prop":"生物"
    },{
        "val":"9",
        "prop":"政治"
    },{
        "val":"12",
        "prop":"科学"
    }]
},{
    "val":"1",
    "prop":"初一",
    "subject":[{
        "val":"1",
        "prop":"语文"
    },{
        "val":"2",
        "prop":"数学"
    },{
        "val":"3",
        "prop":"英语"
    },{
        "val":"4",
        "prop":"物理"
    },{
        "val":"5",
        "prop":"化学"
    },{
        "val":"6",
        "prop":"历史"
    },{
        "val":"7",
        "prop":"地理"
    },{
        "val":"8",
        "prop":"生物"
    },{
        "val":"9",
        "prop":"政治"
    },{
        "val":"12",
        "prop":"科学"
    }]
}];

export default gradeSubjectData;